# Generated by Django 4.2.8 on 2024-01-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopLooser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(blank=True, max_length=100)),
                ('LTPprice', models.CharField(blank=True, max_length=100)),
                ('PerChanges', models.CharField(blank=True, max_length=100)),
                ('Open', models.CharField(blank=True, max_length=100)),
                ('High', models.CharField(blank=True, max_length=100)),
                ('Low', models.CharField(blank=True, max_length=100)),
                ('Qty', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
